### ISSUE TITLE
Godep save doesn't save dependencies recursively

### ISSUE THREAD

**Issue by antonholmquist** [tools/godep#150]
Godep save doesn't save dependencies of dependencies, it only save the imported dependency. Is this behaviour expected?

**Comment by patrickhoefler** [comment]
Same problem here, and I just found the solution. Good news first: It's not really a godep bug :smile:

I'm developing on a Mac. Local building and testing worked fine. When I ran my project through Travis-CI, it mysteriously failed because `github.com/docker/docker/pkg/units` was missing in `Godeps`.

After a bit of digging around in the Docker source code I found that `github.com/docker/docker/pkg/units` is imported by `github.com/docker/docker/pkg/system` – however it is *only* imported by the file `github.com/docker/docker/pkg/system/meminfo_linux.go`. Because of the `_linux` postfix this file is ignored when I run `go list -json` on my Mac – and therefore it is also ignored by godep. When I run `GOOS=linux go list -json` instead, the dependencies for building on Linux are complete, including the previously missing `github.com/docker/docker/pkg/units`.

The solution for me was to run `GOOS=linux godep save` instead of `godep save`.

**Comment by ezbercih** [comment]
+1

**Comment by apaganobeleno** [comment]
+1

**Comment by freeformz** [comment]
Well this is a godep bug as godep should be smarter. ;-) This is basically a problem where godep uses `go list` and that tool will filter out files that don't match the current OS (like *_linux.go files on OSX) or build tags.

**Comment by yaxinlx** [comment]
@freeformz aggree

**Comment by Raffo** [comment]
Any update on this? I broke the build for the same reason. My solution is to run ```godep save ``` again from scratch and compare with the previous Godeps folder. This seems to be the only safe approach in case of update.

**Comment by freeformz** [comment]
@Raffo What version of godep are you using (godep version)? This is actually fixed in current versions as godep is no longer using `go list`. PS: This may be why a new save is fixed things for you.

Closing because the reported problem is fixed.

**Comment by tsuna** [comment]
For my edification, what does godep use instead of `go list`?

**Comment by freeformz** [comment]
@tsuna look at `list.go`, the main driver being listPackage().
