### ISSUE TITLE
`godep save` inconsistent between platforms

### ISSUE THREAD

**Issue by jzelinskie** [tools/godep#161]
I have some code (closed source :crying_cat_face:) that has a dependency using the `// +build` construct to variably include some of their source files. This leads to dependencies in those files from being excluded if `godep save` is ran on a platform that does not require those files.

If I `godep save` on Mac, it'll build and run perfectly fine on Mac, but if I take that codebase and try and build it on Linux, the Godeps directory will be missing dependencies and will fail to compile. I'm currently resolving this by only doing `godep save`/`godep update` on Linux, but it is not a long-term solution as all of our developers are primarily working on Mac.

**Comment by rnapier** [comment]
I've been playing with ways to address this. It's possible to pass -tags to the "go list" command, so you could pass the tags "darwin linux". That works ok as long as nothing uses the `!` syntax. So if you had a `!linux`, it would not include it even though you'd want it. That's causing me trouble on Windows because some things in the standard library are defined as `!windows` rather than an explicit list of everything else.

The other option is to run `LoadPackages` once for each desired tag and then merge the results. That's probably the way it needs to work, but the code is more complicated.

**Comment by jzelinskie** [comment]
Sorry that I didn't post this earlier: the workaround that we've been using is to just use `GOOS=linux go get -d ./...` for getting dependencies.

**Comment by phinze** [comment]
Hey folks, we just switched to Godep over in hashicorp/terraform and we're running into this problem.

We build Terraform for several platforms and we're running into problems trying to vendor the superset of dependencies without constantly fighting diffs or manually editing metadata.

Have any of you come up with methods for addressing this issue?

> The other option is to run `LoadPackages` once for each desired tag and then merge the results. That's probably the way it needs to work, but the code is more complicated.

We might investigate this as a PR if it sounds like a valid approach to everybody.

**Comment by freeformz** [comment]
What version of godep are you using? At this point godep no longer uses `go list` to resolve any dependencies and processes files/deps for all files except those that include the `appengine` or `ignore` build tags.

**Comment by phinze** [comment]
Hi @freeformz - thanks for the tip! Looks like we were indeed running an older version of godep.

Did a fresh `go get -u` and this seems to be resolved w/ the newer version. 

https://github.com/hashicorp/terraform/pull/4957 looks to have the proper superset dependency list

Since everything seems to be working I believe this (and the linked #174) can be closed. :+1:

**Comment by freeformz** [comment]
Great! Thanks. Closing. For anyone else on this ticket please re-open / post a follow up if, after updating, things aren't working for you.

**Comment by jzelinskie** [comment]
@freeformz, I've encountered a similar issue on v52 when recently vendoring. I need to double check to see if it is also caused by `+build` or something else, but I did not have all the proper dependencies.

**Comment by freeformz** [comment]
@jzelinskie If so please file that as a separate issue unless someone else has already done so. ;-)
