### ISSUE TITLE
Saving/overriding repo URL

### ISSUE THREAD

**Issue by gelraen** [tools/godep#207]
It would be great if godep had an option for saving the repo URL along with the version. This will allow to easily maintain a fork of an external package without having to rewrite import path (which makes exchanging code back and forth cumbersome).

**Comment by abourget** [comment]
+111 !

**Comment by hectorj** [comment]
:+1:

**Comment by freeformz** [comment]
If you are "forking" a repo for temporary fixes / updates and plan on merging things up stream I suggest just adding the fork as a remote to the original package.

If you are not then you want to change all/any of the package paths anyway as you're effectively working on a different package.

**Comment by gelraen** [comment]
That's what we doing right now. But there are a few problems with that approach:
1) it requires an external thing (e.g. Makefile) to fetch the repo you need
2) `go get -u` freaks out and fail when the remote URL doesn't match what it expects

**Comment by freeformz** [comment]
@gelraen Why does it require a makefile?

1. I am using package X (which is also a github repo) in my project Y. The package I am using is vendored in the Godep workspace (or vendor/) of my project.
1. I find a bug in package X, so I fork it on github.
1. I cd $GOPATH/src/<PKG X> and `git remote add freeformz https://github.com/freeformz/X.git
1. I create a branch, fix the bug, commit, `git push freeformz bug_fix_branch`.
1. I go to gituhb and open a PR against X with my fixes.
1. I go to project Y on the filesystem ($GOPATH/src/github.com/freeformz/Y) and `godep update X`, which vendors what I currently have for X in my $GOPATH. I commit those vendored changes and push them to my public (or private) repo.
1. Other's pull my code, with the vendored bits and use the vendored versions because they are in my repo and I'm using either a) rewriting; b) the GO15VENDOREXPERIMENT or; c) `godep go install ./...` (my recommended order btw).

Now eventually the upstream either merges my changes or I do in fact need to fork the project and maintain something else.

If they merge my changes I can checkout master on project X in my $GOPATH and `godep update X` in project Y, commit and push.
