### ISSUE TITLE
Respect .gitignore (or git ls-files) when copying

### ISSUE THREAD

**Issue by abourget** [tools/godep#212]
I'm working on a package called `alchemist`. In there, I built binaries for 4 platforms, and I have sensitive config files. That's why I put all of those things in the .gitignore file.. so they're not committed to the repo.

This repo is in my GOPATH, and I work on it from time to time.

Now I have another repo, called `bazooka-joe`, which uses `alchemist`.  When I `godep save` in `bazooka-joe`, it copies *everything* from the `alchemist` repo.. including my sensitive files and phat binaries.

Couldn't godep merely copy the files that *are* in that revision (with `git ls-files` or something) ?

**Comment by abourget** [comment]
no ? :)

**Comment by abourget** [comment]
Couldn't https://github.com/tools/godep/blob/master/save.go#L265-L292 be replaced by some:

```
output, err = exec.Command("git", "ls-files").Output()
for _, file := range outputLines {
    copyPkgFile(file)
}
...

and some equivalent for Mercurial ?  Do you see a problem doing that ?

I'd implement it if you think it could get merged.

**Comment by alexandercampbell** [comment]
+1 to this issue, I frequently hit the same thing.

**Comment by conslo** [comment]
With git and mercurial this could actually be solved by using the respective tool (ie: `git clone $DIRECTORY` instead of copying). I don't know about bzr, but I imagine it's pretty similar. This would mean until you make a commit you can't save the repo into your Godeps.

But regardless of the more plumbing-style approach suggested above, or this, this alludes to another issue: if you're using a locally edited version of the repo, how does the tool know you're not depending on files that are .gitignored? It doesn't, of course, and it's unrealistic to expect it to.

With my suggestion, there are four options I see (much of the same concerns are present in the suggestion above as well):

1. Let it go, if someone does `godep save` with uncommitted code in a dependency they're going to break things, sorry!
1. Don't support copying local dependencies.
1. For each tool that's supported, do a check to see if there's uncommitted changes (git status, etc).
1. When it's detected that we're copying a locally edited dependency print a warning, every time, about how uncommitted code doesn't get copied (or, with the other suggestion, about how .gitignored files don't get copied).

1 feels irresponsible to me. 2 is removing support for a workflow that's incredibly useful when orchestrating cross-library/project changes. 3 will be a lot of work, and could get very complicated and error prone, even more so if we want to take into consideration possible dependencies on .gitignored files. 4 feels like the best option to me; alert developers to the potential issues of what they're doing, which will usually just amount to "oh that test broke, has to do with that warning that's on my screen every time I install dependencies"

**Comment by abourget** [comment]
No 4 seems good to me !

**Comment by itsjamie** [comment]
I didn't realize that it didn't respect .gitignore when I adding Godeps to an existing project and accidentally committed some local test fixtures (large video files) across a few repos that brought in the one project. Oops!

Our local Stash server wasn't too happy with receiving those. :imp:

**Comment by freeformz** [comment]
As of 9570f62c8b83f643855711292495c37ebd2ceffc, godep uses the vcs list command, so that should close this. If I'm not understanding things right please re-open.
