### ISSUE TITLE
godep restore tries to mess with packages in $GOROOT

### ISSUE THREAD

**Issue by steveeJ** [tools/godep#251]
The following happens in a project in $GOPATH

```
$ godep restore
# cd /usr/lib/go/src/golang.org/x/net/html; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
# cd /usr/lib/go/src/golang.org/x/net/html; git checkout 1dfe7915deaf3f80b962c163b918868d8a6d8974
fatal: Not a git repository (or any of the parent directories): .git
godep: restore: exit status 128
# cd /usr/lib/go/src/golang.org/x/tools/go/vcs; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
# cd /usr/lib/go/src/golang.org/x/tools/go/vcs; git checkout 27e692e6ec36d8f48be794f32553e1400c70dbf2
fatal: Not a git repository (or any of the parent directories): .git
godep: restore: exit status 128
```

Everything in $GOROOT has been installed by my distro's package manager, so I don't want to mess with it manually in any way. IMO, godep should leave everything in $GOROOT alone.

**Comment by freeformz** [comment]
How do I reproduce this?

**Comment by kr** [comment]
(I am assuming your GOROOT is `/usr/lib/go`; you can check this by running `go env`.)

Godep tries to update packages on disk wherever they are found; if they are not found, it downloads them to the first entry in GOPATH, just like 'go get'.

I would guess that `/usr/lib/go/src/golang.org/x/net/html` was created somehow outside of godep, and now that it exists, godep finds the package there and tries to update it. Or perhaps the first item in your GOPATH is `/usr/lib/go`—if so, you should remove it. The value of GOROOT should not be in GOPATH.

**Comment by steveeJ** [comment]
@kr 
Right, GOROOT is `/usr/lib/go` and the package via the package manager of my distro. This means no other utility should try to touch that.

My suggestion remains that godep skips every package found under GOROOT. 
If the same package is found in GOROOT and GOPATH it should prefer the one from GOPATH since that's what can be controlled by the user.

**Comment by kr** [comment]
Commands 'godep restore' and 'godep get' follow the same rules as the go tool for locating and downloading packages. That will remain the case. (In fact, godep doesn't download any packages itself, it just runs the go tool to do that work. Any behavior change there would have to happen in the go tool.)

You should remove the value of GOROOT from your GOPATH, if it's there. I also recommend you delete golang.org/x/net/html from your GOROOT, along with any other packages in GOROOT that aren't part of the standard library. That should get you back up and running, so that both 'godep restore' and 'go get' work properly for all packages.

**Comment by sundarv85** [comment]
@kr 
This is the folder arch for my development.  Please let me know what is the expected method for using godep.

~/go
~/go/src/company_repo/project
~/go/src/company_repo/project/subprojA
~/go/src/company_repo/project/subprojB
~/go/src/company_repo/project/Godeps
~/go/src/company_repo/project/Godeps/src
~/go/src/company_repo/project/Godeps/src/workspace

Since we are more than one developer, we do not maintain any source in our ~/go/src other than our company_repo.

All the golang sources are vendored into Godeps/src/workspace by using `godep`

Now the problem is, when I want to now add another dependency, I’m now forced to do the following:

godep restore
godep get <new dependecy> `or` go get <new dependecy> (both are same)
godep save ./...

Wouldn’t it be easier if godep get will directly save it into Godeps/src/workspace

If that is not the intention of godep, then what is the correct way to make the above work without the need to `godep restore`.

**Comment by freeformz** [comment]
@sundarv85 rewrite your import paths (the -r option) is the way to work around having to use `godep restore` for the common cases (you will still need to do this before a `godep update` though).
