### ISSUE TITLE
No such file or directory with github.com/gosexy/exif 

### ISSUE THREAD

**Issue by fesja** [tools/godep#272]
Hi,

I'm starting with godep and I'm having a problem with the library [github.com/gosexy/exif](https://github.com/gosexy/exif).

    RUN godep go test

    # github.com/gosexy/exif
    Godeps/_workspace/src/github.com/gosexy/exif/main.go:35:10: fatal error: '_cgo/types.h' file not found
    #include "_cgo/types.h"
             ^
    1 error generated.
    godep: go exit status 2

that file is inside the repo https://github.com/gosexy/exif/blob/master/_cgo/types.h

Any idea on why is it failing?

thanks a lot!

**Comment by freeformz** [comment]
What version of godep are you using? What is the output of `godep version`?
Can you link to your repo or is it private?
Can you provide a publicly accessible reproduction (a public repo with a project the shows this issue)?

**Comment by neurogeek** [comment]
This happens because the _cgo directory is ignored (because it starts with _) when vendoring github.com/gosexy/exif, then when godep go build tries to build it, it fails because it is missing the required src file.

This wouldn't be a problem if the dir was called cgo instead of _cgo. Same thing happens with _examples, so you won't be able to run tests in the vendored package.

I don't think we can change anything here.

**Comment by fesja** [comment]
Thanks Jesús, I ended up not using godep as I was in a rush. But i will look at it in the future.






On Wed, Sep 9, 2015 at 12:12 AM -0700, "Jesus Rivero" <notifications@github.com> wrote:












Closed #272.

**Comment by freeformz** [comment]
@neurogeek Doh. I blame being up early for the first day of school for not realizing that. ;-)

**Comment by neurogeek** [comment]
@freeformz It's all good, man! :D
