### ISSUE TITLE
Godep not handling nested packages cleanly

### ISSUE THREAD

**Issue by Alex-Addy** [tools/godep#303]
When having a package inside a git repo alongside another package `godep save` will fail when the git repo state is dirty.

The situation is just about

```
.
|--dirty
|    |----Godeps
|    |        \...
|    \ main.go
|--help
    \ help.go
```

With help being in its own package and main using that package. The problem comes down to being unable to have a dirty main and run the `godep save` command, as the git state is global to a repo and a dirty file anywhere will cause `help.go` to be considered dirty. This makes it very difficult to use go's packages to split up functionality 

Also godep will put help into the Godeps directory. Causing it to be duplicated inside the same repo.

I have made a repo to demonstrate this at https://github.com/Alex-Addy/godep_nested_packages.git
To reproduce clone the repo, modify main.go (ex `echo "//" >> main.go`), then run `godep save` inside dirty.

Are there any suggestions on how to get around this? Or maybe an explanation on why it was considered necessary to do this check?

A possible solution would be to allow for skipping the `vcs.IsDirty` check in general or on those packages in the same repo via a command line flag.

**Comment by freeformz** [comment]
What is the vcs root in the above example? I assume it's the parent directory of `dirty` and `help` as in the example?

**Comment by rasky** [comment]
This should be fixed by my pull #302

**Comment by freeformz** [comment]
@rasky I am trying to understand what's going on here and the motivators. Godep is designed to be run in the top package of a repo. There is nothing ATM in your PR BTW.

**Comment by rasky** [comment]
What you mean "there's nothing"? It's a one character patch. It's small, but it's effective :) I think my pull description tries to explain the issue, but I can try again. There are many git repos which are COLLECTIONS of packages, not just single packages. This is especially visibile in /x/ repos. If you import `golang.com/x/crypto/ssh` and run go get, you will get a full checkout of `golang.com/x/crypto` which is a single git repository including dozens of different packages (see: https://github.com/golang/crypto). Now let's say that for another project you locally modify a file within `golang.com/x/openpgp`, in your GOPATH. If you later run `godep save` on the first project (the one using `golang.com/x/crypto/ssh`), you get a dirty error by godep, because the modification in your copy of `golang.com/x/openpgp` is wrongly seen as a modification affecting your project; but your project uses `golang.com/x/crypto/ssh`, not `golang.com/x/crypto/openpgp`, so there is not need to abort the `godep save` operation.

My one-character PR fixes this.

**Comment by freeformz** [comment]
Sorry, I missed the `.` in the diff (I thought it was only a space via a quick glance). My bad.

Re: description.

As I said godep is designed to work against the top level package of a repo. You are asking for a fundamental change to the tool.

**Comment by rasky** [comment]
If you run "godep save" on a project importing `golang.org/x/crypto/ssh`, only the `ssh` package is vendored. So I'm not sure what you mean with "designed to work against the top level package of a repo", since it already works the way I expect.

**Comment by freeformz** [comment]
PS: I guess I've already started that fundamental change with previous changes, so I'll have to think about this more.

**Comment by freeformz** [comment]
@rasky That's for a dependency, not for the repo you are vendoring into. In your example, let's say `golang.org/x/crypto/ssh` needed to vendor something, `godep save` should only be run at the `golang.org/x/crypto` level.

**Comment by rasky** [comment]
Oh now I see. My way of reading the OP post was the same of the bug I pursuing, so the fact that you can't vendor a perfectly clean dependency because of an unrelated modification in THEIR repository, and I felt that the fact that it was putting main in a subdirectory was just an unimportant detail. So we have two issues here:

1) unrelated modifications in the same git repo of a dependency. This is fixed by PR
2) running godep in a subdirectory of a git repo. This is unrelated to the first issue, and possibly a larger change to godep.

**Comment by Alex-Addy** [comment]
The problem is that once one starts using godep, one has to always use godep to build and such. The vcs.IsDirty check is preventing us from always using godep during development. Making it more difficult to develop against exactly what the release build will be using. #305 will allow us to develop using the flag, then remove it when building for release, letting us use the sanity check only when needed.

**Comment by freeformz** [comment]
@Alex-Addy You do not need to use godep to build if you a) rewrite your deps or b) are using go1.5+ with the GO15VENDOREXPERIMENT=1. Both of those are recommended over using godep to build.

**Comment by freeformz** [comment]
@Alex-Addy godep should only be used from the root package of a repo. If a repo contains multiple packages you should not be running `godep save` in each package, but in the root package for that repo and use a more inclusive package selector (`./...`, `./<dira> ./<dirb>`, etc).

**Comment by Alex-Addy** [comment]
I am closing this issue as it is very old and we no longer use godep. It also looks like to be contrary to the intended use of the tool, which is never good.
