### ISSUE TITLE
Bug in godep restore

### ISSUE THREAD

**Issue by SDkie** [tools/godep#345]
https://github.com/tools/godep/commit/bd1a5cd1a59bff09fa53022436490eb03fb0dc4c

Above commit has some issue. 'go dep restore' is giving me following error : "godep: error restoring dep (github.com/chai2010/webp): found packages webp (bench_test.go) and main (gen_helper.go) in /go/src/github.com/chai2010/webp"

Before that commit it was working properly.

**Comment by krnowak** [comment]
I tried to fix this, but it is usually the package that needs to be fixed actually. Normally, you should not have two files in a directory with two different package names (like `bench_test.go` has a package `webp` and `gen_helper.go` has a package `main`).

This is a fallout from moving away from `go list` in favor of `go/build` package.

Usually, this kind of bug is because that often helper binaries have "main" package and a `// +build ignore` constraint. The constraint was enough for `go list` to ignore the file alright. But after the switch, the [`UseAllFiles`](https://golang.org/pkg/go/build/#Context) field is set to true by default, so it takes all the files, not taking `// +build` constraints into account at all.

Probably the proper solution would be to fix the offending package, but I tried to somehow work it around and failed.

**Comment by freeformz** [comment]
"Fixed" in #352 as we'll also ignore the "ignore" build tag, at least for now. I think that's the path of least surprise.
