### ISSUE TITLE
cannot find package "appengine"

### ISSUE THREAD

**Issue by gyuho** [tools/godep#353]
Build failed for the following code:

```
package main

import "google.golang.org/appengine"

func main() {
	_ = appengine.AccessToken
}
```

I ran: 

```
godep save -t -r ./...
godep: cannot find package "appengine" in any of:
	/usr/local/go/src/appengine (from $GOROOT)
	/home/gyuho/go/src/appengine (from $GOPATH)
```

Could you take a look?

I tried it after this PR https://github.com/tools/godep/pull/341.

Thanks,

**Comment by freeformz** [comment]
[`identity_classic.go`](https://github.com/golang/appengine/blob/7f9f17f358c21d90f402980f83776898c53cb377/internal/identity_classic.go) is importing "appengine". Since this is guarded by a build tag `go list -e -json google.golang.org/appengine` wouldn't pick it up, so it worked. 

We now parse all files regardless of build tag and "appengine" isn't a valid import (except on appengine probably).

```console
$ go list -e -json appengine
{
	"ImportPath": "appengine",
	"Stale": true,
	"Incomplete": true,
	"Error": {
		"ImportStack": [
			"appengine"
		],
		"Pos": "",
		"Err": "cannot find package \"appengine\" in any of:\n\t/usr/local/go/src/appengine (from $GOROOT)\n\t/Users/emuller/go/src/appengine (from $GOPATH)"
	}
}
```

**Comment by freeformz** [comment]
I'm not 100% sure what to do about this (aside from full build tag support for godeps). I may just special case "appengine" for now to unblock anyone hitting this issue and then remove that special case if/when full build tag support materializes.

**Comment by gyuho** [comment]
Thanks!
