### ISSUE TITLE
warning about GO15VENDOREXPERIMENT showing up even though it's not set

### ISSUE THREAD

**Issue by shawnps** [tools/godep#433]
Hi,

I get this error every time I invoke `godep` now:

`godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists`

but `$GO15VENDOREXPERIMENT` is not set:

```
➜  ~ echo $GO15VENDOREXPERIMENT
```

**Comment by shawnps** [comment]
I see I can do 

`export GO15VENDOREXPERIMENT=0` and it will go away, but for new terminals of course the warning will still show up unless I explicitly put `export GO15VENDOREXPERIMENT=0` into my shell rc.

I'm guessing this is why:

`(v == "go1.6" && go15ve != "0")`

I'm fine putting `export GO15VENDOREXPERIMENT=0` into my shell rc for now, so feel free to close this if you'd prefer not to take action on it.

**Comment by freeformz** [comment]
This warning is there to tell you that your combo version of go and config vars is telling godep to use the vendor experiment, but godep disables it because it found an existing old style godep workspace. 

Exporting GO15VENDOREXPERIMENT=0 disables the vendor experiment, so the warning goes away.

Maybe I should make the warning clearer somehow?

**Comment by shawnps** [comment]
@freeformz it's okay, I just thought that not having the `GO15VENDOREXPERIMENT` set at all should be the same as having it set to GO15VENDOREXPERIMENT=0. No worries.
