### ISSUE TITLE
save fails when copying sym links

### ISSUE THREAD

**Issue by fkm3** [tools/godep#57]
```
$ godep save ./...
godep: read /home/fred/code/go/src/github.com/valyala/ybc/bindings/go/ybc/platform: is a directory
godep: error copying source code
```

**Comment by vcaputo** [comment]
@kr It needs to recur at the symlink, not simply preserve the symlink.

Imagine a project `foo.com/bar` where the directory structure is like this:
> bin/
> doc/
> some_pkg -> src/some_pkg
> src/
> Makefile
> README

The symlink is included just to cleanup the import path of some_pkg for external users:
`import "foo.com/bar/some_pkg"`
vs.
`import "foo.com/bar/src/some_pkg"`

While still allowing the project to have a clean separation of the code from everything else in the directory structure.

But if a project imports the path at the symlink and `godep save` is used, all it saves is the symlink.

**Comment by kr** [comment]
Godep can't simply follow symlinks, because that can result in pathological behavior. (Consider a symlink that points to its parent directory.) Godep is in a similar situation to the standard go tool with respect to symlinks. As Ian Lance Taylor [put it](https://groups.google.com/d/msg/golang-dev/GLUZGtUSj8A/SGUtCooLIT0J):

> Yes.  In general the go tool does not work well with symlinks.  There
is no current plan to change this.  Any fix would have to describe a
complete and coherent solution for how symlinks should be handled.  I
don't know what that would look like.

Godep is in the same boat.
