### ISSUE TITLE
Add support for -tags

### ISSUE THREAD

**Issue by whatupdave** [tools/godep#59]
In my project (https://github.com/asm-products/readraptor) I'm using `Goose` for migrations and need to install a binary on Heroku. I'm using:

    // +build heroku

    package main

    import _ "bitbucket.org/liamstask/goose/cmd/goose"

`godep save` fails to pick up the dependency. On Heroku, install runs with `godep go install -tags heroku ./...`

I think `godep save -tags heroku ./...` would fix the issue.

**Comment by cpmech** [comment]
Hi, I'm just wondering if there is any updates on this? Cheers. D

**Comment by maxpersson** [comment]
+1 for this. We would like to use it for including mocks only in the test run and not final build.

**Comment by phemmer** [comment]
> For your particular case, is there a reason you can't put the import in a regular source file, without any build constraints?

You could do this, but in the case of goose, it pulls in a lot of deps that take a while to build. Thus when developing locally, `go test` takes quite some time to build things it doesn't need.

As another proposal, I think it would be nice for `godep` to automatically add a `godep` tag on all operations it performs (`go list`). This would allow creating dummy files with the `godep` tag so that additional packages (which aren't build or test deps) are vendored, and won't require passing the `-tags` flag all the time.

**Comment by freeformz** [comment]
atm as long as the imported package has files with build tags that include it on the local machine (a file with `// +build heroku` and a different file with `// +build !heroku`) both files will be included (assuming they are both committed to vcs). Ultimately we want to vendor everything regardless of tags so that code is buildable in multiple environments. See #271. I'm closing this for now in favor of that issue.
