### ISSUE TITLE
local import "./web" in non-local package

### ISSUE THREAD

**Issue by john-qin** [tools/godep#90]
when I use "godep save", I got following error message

godep: local import "./web" in non-local package
godep: error loading packages

here's my gopath:
GOPATH="/Users/johnqin/projects/go"

my go application lives in this folder.
/Users/johnqin/projects/go/src/poc

here's my file structure

- go
  - server.go
  - web
     - config.go
     - db.go
     - handlers.go
     - ......

 all files in hte web folder are under the package web.
in my server.go, i am using
import "./web"

what do i need to change to make "godep save" working?

**Comment by sosiouxme** [comment]
Can I ask *why* one should never use relative imports in Go source code? Go supports it, it seems like a completely natural thing to do, and there are some good use cases for doing this even within the recommended code organization.

Say I create a library that I would *like* people to fork. It's available at github.com/foo/bar, but if I put that in its own import paths, then when someone forks it to github.com/baz/quux, they have some lousy choices for enabling others to use it:

1. Go through and update all the paths from foo/bar to baz/quux. Straightforward enough, but now if we want to cherry-pick each other's commits, there's probably a merge conflict every time one of us adds or removes an import.
2. Tell people `go get github.com/foo/bar`, then add github.com/baz/quux as a remote and set up master to track that instead... awkward and confusing
3. Tell people `git clone github.com/baz/quux` and then put that dir in your $GOPATH at foo/bar... also awkward and confusing.

If my library used `import "./subdir"` everywhere then none of this is a problem, you could just `go get github.com/baz/quux` and the fact that you're using a fork is clear and simple... except for godep, and let's face it, I'm gonna want a YAML parser, I'm gonna want systemd integration, etc. etc. so I will want godep to manage dependencies. As an added bonus, it's really easy to distinguish within a tenth of a second which imports are local versus some dependency. If Go can manage it, why is it so hard in godep to just treat "./subdir" and "../subdir" as ... local to the package?

**Comment by sosiouxme** [comment]
Looks like it might be as simple as https://github.com/tools/godep/pull/130/files ?

**Comment by duggan** [comment]
Ran into this after trying to vendorize an autogenerated protocol buffers library.

`import ./mypackage` is valid Go, and Go is pretty strict about what it allows. This is a bug in Godep.

**Comment by freeformz** [comment]
@duggan Why would you not import it as `<canonical>/<package>/<sub package>` ?

For instance when I have a "local" package of some sort I'll import it like `github.com/freefromz/mypackage/subpackage` instead of `./subpackage`.

Or do you always work outside of  `$GOPATH` (which AFAIK is the only place local imports work properly ... but I could be wrong)?

Also, AFAIK, relative import paths are discouraged.

**Comment by sosiouxme** [comment]
@freeformz Relative import paths are discouraged... why? By whom?

**Comment by kr** [comment]
Relative paths in import statements are prohibited inside a work space.
https://golang.org/cmd/go/#hdr-Relative_import_paths

Godep isn't going to make any effort to support something the standard 'go' tool doesn't.

**Comment by steenzout** [comment]
@sosiouxme just got this exact same problem when trying to contribute to a Go open source project.
travis-ci build just fails.

**Comment by steenzout** [comment]
@sosiouxme it seems you can use `go_import_path: example.org/pkg/foo` on your `.travis.yml` file to make it work.

**Comment by freeformz** [comment]
@steenzout What project?

**Comment by steenzout** [comment]
after re-reading this thread I think the problem is more related to how people want to use `go dep`.
my case was just a simple problem with travis-ci builds on different github repos (google led me here).
I was trying to use relative imports to solve the problem which then gave me the same non-local package error.

here are the repos:
- [mediaFORGE/gol](https://github.com/mediaFORGE/gol)
- [steenzout/gol](https://github.com/steenzout/gol)

adding `go_import_path` on the `.travis.yml` file made builds work on my `steenzout` account.
now anyone can fork the [mediaFORGE/gol](https://github.com/mediaFORGE/gol) repo and test their changes using travis-ci.org (after enabling it for their forked repo, of course).
no need for relative imports.

sorry for the spam.
